# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CcDashboard < Formula
  desc "実行中の Claude Code セッション一覧を表示する TUI"
  homepage "https://github.com/ToshihitoKon/cc-dashboard-tui"
  version "1.0.0-alpha.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ToshihitoKon/cc-dashboard-tui/releases/download/v1.0.0-alpha.4/cc-dashboard_1.0.0-alpha.4_darwin_amd64.tar.gz"
      sha256 "7eee05cea1f8ab3662aec1927e5b837835825741766c33b534ce0f86df014274"

      define_method(:install) do
        bin.install "cc-dashboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ToshihitoKon/cc-dashboard-tui/releases/download/v1.0.0-alpha.4/cc-dashboard_1.0.0-alpha.4_darwin_arm64.tar.gz"
      sha256 "e04b15f7de104a5ffedc2de0e9004fc549ce96cfc0154cad113a29a60e7174eb"

      define_method(:install) do
        bin.install "cc-dashboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ToshihitoKon/cc-dashboard-tui/releases/download/v1.0.0-alpha.4/cc-dashboard_1.0.0-alpha.4_linux_amd64.tar.gz"
      sha256 "3024ccbf9d7e96e09f36842873b47356c1733aa478bb2ea1a30b8122d81643ff"
      define_method(:install) do
        bin.install "cc-dashboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ToshihitoKon/cc-dashboard-tui/releases/download/v1.0.0-alpha.4/cc-dashboard_1.0.0-alpha.4_linux_arm64.tar.gz"
      sha256 "83f950e56cb6e3a1e637fbb90135bc61bb3304311e2e3b51ffce8d5049a47c4e"
      define_method(:install) do
        bin.install "cc-dashboard"
      end
    end
  end
end
